webdoan/Areas/Admin/Controllers/AdminProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using webdoan.Areas.Admin.Models;
using webdoan.Helpper;
using webdoan.Models;

namespace webdoan.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminProductsController : Controller
    {
        private readonly DataContext _context;

        public AdminProductsController(DataContext context)
        {
            _context = context;
        }

        // GET: Admin/AdminProducts
        public async Task<IActionResult> Index()
        {
              return View(await _context.Products.ToListAsync());
        }

        // GET: Admin/AdminProducts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var products = await _context.Products
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (products == null)
            {
                return NotFound();
            }

            return View(products);
        }

        // GET: Admin/AdminProducts/Create
        public IActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,ProductName,ShortDesc,Description,CatId,Price,Discount,Thumb,Video,DateCreated,DateModified,BestSellers,HomeFlag,Active,Tags,Title,Alias,MetaDesc,MetaKey,UnitsInStock")] Products products, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (ModelState.IsValid)
            {
                products.ProductName = Utilities.ToTitleCase(str: products.ProductName);
                if (fThumb != null)
                {
                    string extension = Path.GetExtension(fThumb.FileName);
                    string image = Utilities.SEOUrl(products.ProductName) + extension;
                    products.Thumb = await Utilities.UploadFile(fThumb, @"products", image.ToLower());
                }
                if (string.IsNullOrEmpty(products.Thumb)) products.Thumb = "default.jpg";
                products.Alias = Utilities.SEOUrl(products.ProductName);
                products.DateModified = DateTime.Now;
                products.DateCreated = DateTime.Now;

                _context.Add(products);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(products);
        }

        // GET: Admin/AdminProducts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var products = await _context.Products.FindAsync(id);
            if (products == null)
            {
                return NotFound();
            }
            return View(products);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,ProductName,ShortDesc,Description,CatId,Price,Discount,Thumb,Video,DateCreated,DateModified,BestSellers,HomeFlag,Active,Tags,Title,Alias,MetaDesc,MetaKey,UnitsInStock")] Products products, Microsoft.AspNetCore.Http.IFormFile fThumb)
        {
            if (id != products.ProductId)
            {
                return NotFound();
            }

           
            if (ModelState.IsValid)
                {
                    products.ProductName = Utilities.ToTitleCase(str: products.ProductName);
                    if (fThumb != null)
                    {
                        string extension = Path.GetExtension(fThumb.FileName);
                        string image = Utilities.SEOUrl(products.ProductName) + extension;
                        products.Thumb = await Utilities.UploadFile(fThumb, @"products", image.ToLower());
                    }
                    if (string.IsNullOrEmpty(products.Thumb)) products.Thumb = "default.jpg";
                    products.Alias = Utilities.SEOUrl(products.ProductName);
                    products.DateModified = DateTime.Now;
                  

                    _context.Update(products);
                    await _context.SaveChangesAsync();

                    return RedirectToAction(nameof(Index));
            }
                return View(products);
            
        }

        // GET: Admin/AdminProducts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var products = await _context.Products
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (products == null)
            {
                return NotFound();
            }

            return View(products);
        }

        // POST: Admin/AdminProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Products == null)
            {
                return Problem("Entity set 'DataContext.Products'  is null.");
            }
            var products = await _context.Products.FindAsync(id);
            if (products != null)
            {
                _context.Products.Remove(products);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductsExists(int id)
        {
          return _context.Products.Any(e => e.ProductId == id);
        }
    }
}

webdoan/Areas/Admin/Views/AdminProducts/Create.cshtml
@model webdoan.Areas.Admin.Models.Products

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<main int id="main" class="main">
<h1>Create</h1>

<h4>Products</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="AdminProducts" asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShortDesc" class="control-label"></label>
                <input asp-for="ShortDesc" class="form-control" />
                <span asp-validation-for="ShortDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CatId" class="control-label"></label>
                <input asp-for="CatId" class="form-control" />
                <span asp-validation-for="CatId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Discount" class="control-label"></label>
                <input asp-for="Discount" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Thumb" class="control-label"></label>
                <input name="fThumb" type="file" asp-for="Thumb" class="form-control" />
                <span asp-validation-for="Thumb" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Video" class="control-label"></label>
                <input asp-for="Video" class="form-control" />
                <span asp-validation-for="Video" class="text-danger"></span>
            </div>
            
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="BestSellers" /> @Html.DisplayNameFor(model => model.BestSellers)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="HomeFlag" /> @Html.DisplayNameFor(model => model.HomeFlag)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Tags" class="control-label"></label>
                <input asp-for="Tags" class="form-control" />
                <span asp-validation-for="Tags" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Alias" class="control-label"></label>
                <input asp-for="Alias" class="form-control" />
                <span asp-validation-for="Alias" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MetaDesc" class="control-label"></label>
                <input asp-for="MetaDesc" class="form-control" />
                <span asp-validation-for="MetaDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MetaKey" class="control-label"></label>
                <input asp-for="MetaKey" class="form-control" />
                <span asp-validation-for="MetaKey" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitsInStock" class="control-label"></label>
                <input asp-for="UnitsInStock" class="form-control" />
                <span asp-validation-for="UnitsInStock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
</main>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

webdoan/Areas/Admin/Views/AdminProducts/Delete.cshtml
@model webdoan.Areas.Admin.Models.Products

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<main int id="main" class="main">
<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Products</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShortDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShortDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CatId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CatId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Discount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Discount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Thumb)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Thumb)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Video)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Video)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateModified)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateModified)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BestSellers)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BestSellers)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HomeFlag)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HomeFlag)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tags)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tags)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Alias)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Alias)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MetaDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MetaDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MetaKey)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MetaKey)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UnitsInStock)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UnitsInStock)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</main>

webdoan/Areas/Admin/Views/AdminProducts/Details.cshtml
@model webdoan.Areas.Admin.Models.Products

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<main int id="main" class="main">
<h1>Details</h1>

<div>
    <h4>Products</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShortDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShortDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CatId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CatId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Discount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Discount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Thumb)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Thumb)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Video)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Video)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateModified)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateModified)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BestSellers)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BestSellers)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HomeFlag)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HomeFlag)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tags)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tags)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Alias)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Alias)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MetaDesc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MetaDesc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MetaKey)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MetaKey)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UnitsInStock)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UnitsInStock)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ProductId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
</main>

webdoan/Areas/Admin/Views/AdminProducts/Edit.cshtml
@model webdoan.Areas.Admin.Models.Products

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<main int id="main" class="main">
<h1>Edit</h1>

<h4>Products</h4>
<hr />
<div class="row">
    <div class="col-md-4">
            <form asp-controller="AdminProducts" asp-action="Edit" asp-route-id="@Model.ProductId" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProductId" />
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShortDesc" class="control-label"></label>
                <input asp-for="ShortDesc" class="form-control" />
                <span asp-validation-for="ShortDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CatId" class="control-label"></label>
                <input asp-for="CatId" class="form-control" />
                <span asp-validation-for="CatId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Discount" class="control-label"></label>
                <input asp-for="Discount" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>
                <div class="form-group">
                    <label asp-for="Thumb" class="control-label"></label>
                    <input name="fThumb" type="file" asp-for="Thumb" class="form-control" />
                    <span asp-validation-for="Thumb" class="text-danger"></span>
                </div>
            <div class="form-group">
                <label asp-for="Video" class="control-label"></label>
                <input asp-for="Video" class="form-control" />
                <span asp-validation-for="Video" class="text-danger"></span>
            </div>
            
            
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="BestSellers" /> @Html.DisplayNameFor(model => model.BestSellers)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="HomeFlag" /> @Html.DisplayNameFor(model => model.HomeFlag)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Tags" class="control-label"></label>
                <input asp-for="Tags" class="form-control" />
                <span asp-validation-for="Tags" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Alias" class="control-label"></label>
                <input asp-for="Alias" class="form-control" />
                <span asp-validation-for="Alias" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MetaDesc" class="control-label"></label>
                <input asp-for="MetaDesc" class="form-control" />
                <span asp-validation-for="MetaDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MetaKey" class="control-label"></label>
                <input asp-for="MetaKey" class="form-control" />
                <span asp-validation-for="MetaKey" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitsInStock" class="control-label"></label>
                <input asp-for="UnitsInStock" class="form-control" />
                <span asp-validation-for="UnitsInStock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
</main>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

webdoan/Areas/Admin/Views/AdminProducts/Index.cshtml
@model IEnumerable<webdoan.Areas.Admin.Models.Products>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<main int id="main" class="main">
    <div class="pagetitle">
        <h2>Danh sách sản phẩm</h2>
    </div>
    <p>
        <a type="button" class="btn btn-success" asp-area="Admin" asp-controller="AdminProducts" asp-action="Create">
            <i class="bi bi-file-earmark-text me-1"></i> Thêm sản phẩm
        </a>
    </p>
    <section class="section dashboard">
        <div class="row">
            <div class="col-12">
                <div class="card recent-sales overflow-auto">
                    <div class="card-body mt-4">
                        <table class="table table-borderless datatable">
                            <thead>
                                <tr>
                                    <th class="col-1 text-center">#</th>
                                    <th class="col-3 text-center">Tên sản phẩm</th>
                                    <td class="col-2 text-center">Giá</td>
                                    <td class="col-2 text-center">Đang còn</td>
                                    <td class="col-1 text-center">Danh mục</td>
                                    <td class="col-1 text-center">Hiển thị</td>
                                    <th class="col-2 text-center">Chức năng</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <th class="text-center" scope="row">@item.ProductId</th>
                                        <td>
                                            <a asp-area="Admin" asp-controller="AdminProducts" asp-action="Details"
                                           asp-route-id="@item.ProductId" class="text-primary">@item.ProductName</a>
                                        </td>
                                        <td class="text-center">@item.Price</td>
                                        <td class="text-center">@item.Discount</td>
                                        <td class="text-center">@item.CatId</td>
                                        <td class="text-center">@item.Active</td>
                                        <td class="text-center">
                                            <a asp-area="Admin" asp-controller="AdminProducts" asp-action="Details"
                                           asp-route-id="@item.ProductId" class="btn btn-primary btn-sm"
                                           title="chi tiết"><i class="ri-apps-2-line"></i></a>
                                            <a asp-area="Admin" asp-controller="AdminProducts" asp-action="Edit"
                                           asp-route-id="@item.ProductId" class="btn btn-primary btn-sm"
                                           title="Sửa nội dung bài viết"><i class="bi bi-pencil"></i></a>
                                            <a asp-area="Admin" asp-controller="AdminProducts" asp-action="Delete"
                                           asp-route-id="@item.ProductId" class="btn btn-danger btn-sm"
                                           title="Xóa thông tin bài viết"><i class="bi bi-trash"></i></a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </section>
</main>