webdoan/Areas/Admin/Controllers/AdminRolesController.cs
 using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using webdoan.Areas.Admin.Models;
using webdoan.Models;

namespace webdoan.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminRolesController : Controller
    {
        private readonly DataContext _context;

        public AdminRolesController(DataContext context)
        {
            _context = context;
        }

        // GET: Admin/AdminRoles
        public async Task<IActionResult> Index()
        {
              return View(await _context.Role.ToListAsync());
        }

        // GET: Admin/AdminRoles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Role == null)
            {
                return NotFound();
            }

            var role = await _context.Role
                .FirstOrDefaultAsync(m => m.RoleId == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // GET: Admin/AdminRoles/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RoleId,RoleName,Description")] Role role)
        {
            if (ModelState.IsValid)
            {
                _context.Add(role);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Admin/AdminRoles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Role == null)
            {
                return NotFound();
            }

            var role = await _context.Role.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        // POST: Admin/AdminRoles/Edit/5
     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RoleId,RoleName,Description")] Role role)
        {
            if (id != role.RoleId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(role);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoleExists(role.RoleId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Admin/AdminRoles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Role == null)
            {
                return NotFound();
            }

            var role = await _context.Role
                .FirstOrDefaultAsync(m => m.RoleId == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // POST: Admin/AdminRoles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Role == null)
            {
                return Problem("Entity set 'DataContext.Role'  is null.");
            }
            var role = await _context.Role.FindAsync(id);
            if (role != null)
            {
                _context.Role.Remove(role);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoleExists(int id)
        {
          return _context.Role.Any(e => e.RoleId == id);
        }
    }
}

webdoan/Areas/Admin/Views/AdminRoles/Create.cshtml
@model webdoan.Areas.Admin.Models.Role

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<main int id="main" class="main">
<h1>Create</h1>

<h4>Role</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="RoleId" class="control-label"></label>
                    <input asp-for="RoleId" class="form-control" />
                    <span asp-validation-for="RoleId" class="text-danger"></span>
                </div>
            <div class="form-group">
                <label asp-for="RoleName" class="control-label"></label>
                <input asp-for="RoleName" class="form-control" />
                <span asp-validation-for="RoleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
</main>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

webdoan/Areas/Admin/Views/AdminRoles/Delete.cshtml
@model webdoan.Areas.Admin.Models.Role

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<main int id="main" class="main">
<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Role</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoleId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoleId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoleName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoleName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="RoleId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</main>

webdoan/Areas/Admin/Views/AdminRoles/Details.cshtml
@model webdoan.Areas.Admin.Models.Role

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<main int id="main" class="main">
<h1>Details</h1>

<div>
    <h4>Role</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoleId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoleId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoleName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoleName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.RoleId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
</main>

webdoan/Areas/Admin/Views/AdminRoles/Edit.cshtml
@model webdoan.Areas.Admin.Models.Role

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<main int id="main" class="main">
<h1>Edit</h1>

<h4>Role</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RoleId" />
            <div class="form-group">
                <label asp-for="RoleName" class="control-label"></label>
                <input asp-for="RoleName" class="form-control" />
                <span asp-validation-for="RoleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
</main>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

webdoan/Areas/Admin/Views/AdminRoles/Index.cshtml
@model IEnumerable<webdoan.Areas.Admin.Models.Role>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<main int id="main" class="main">
    <div class="pagetitle">
        <h2>Danh sách quyền truy cập</h2>
    </div>
    <p>
        <a type="button" class="btn btn-success" asp-area="Admin" asp-controller="AdminRoles" asp-action="Create">
            <i class="bi bi-file-earmark-text me-1"></i> Thêm tài khoản
        </a>
    </p>
    <section class="section dashboard">
        <div class="row">
            <div class="col-12">
                <div class="card recent-sales overflow-auto">
                    <div class="card-body mt-4">
                        <table class="table table-borderless datatable">
                            <thead>
                                <tr>
                                    <th class="col-1 text-center">#</th>
                                    <th class="col-3 text-center">Tên Role</th>
                                    <td class="col-2 text-center">Mô Tả</td>
                                    
                                    <th class="col-2 text-center">Chức năng</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <th class="text-center" scope="row">@item.RoleId</th>
                                        <td>
                                            <a asp-area="Admin" asp-controller="AdminRoles" asp-action="Details"
                                           asp-route-id="@item.RoleId" class="text-primary">@item.RoleName</a>
                                        </td>
                                        <td class="text-center">@item.Description</td>
                                        
                                        <td class="text-center">
                                            <a asp-area="Admin" asp-controller="AdminRoles" asp-action="Details"
                                           asp-route-id="@item.RoleId" class="btn btn-primary btn-sm"
                                           title="chi tiết"><i class="ri-apps-2-line"></i></a>
                                            <a asp-area="Admin" asp-controller="AdminRoles" asp-action="Edit"
                                           asp-route-id="@item.RoleId" class="btn btn-primary btn-sm"
                                           title="Sửa nội dung bài viết"><i class="bi bi-pencil"></i></a>
                                            <a asp-area="Admin" asp-controller="AdminRoles" asp-action="Delete"
                                           asp-route-id="@item.RoleId" class="btn btn-danger btn-sm"
                                           title="Xóa thông tin bài viết"><i class="bi bi-trash"></i></a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </section>
</main>
<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RoleName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RoleName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.RoleId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.RoleId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.RoleId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>